### ISSUE TITLE
How should I write tests when using dynamodb?

### ISSUE THREAD

**Issue by almondjelly** [castore-dev/castore#66]
I'm using the dynamodb storage adapter and want to use `pushEventTransaction` in one of my commands. What's the right way to write tests for this? Since the mock event store uses an in-memory adapter, I get the error message:

> The event storage adapter of event store ABC is not an instance of DynamoDbEventStorageAdapter and cannot use pushEventTransaction.

**Comment by ThomasAribart** [comment]
Hello @almondjelly and thanks for the heads up !

The transaction API is definitely clunky and needs some rework. I'll try to move the `pushEventTransaction` to the `core` package so that it's not a pb anymore.

Meanwhile, I suggest passing the `pushEventTransaction` via the context arguments of the command.

```ts
const command = new Command({
  ...
   handler: (event, eventStores, { pushEventTransaction }) => { ... }
)}
```

You can then provide a different `pushEventTransaction` between your code and your tests, although it's not completely finished, as you need to mock it to push the said events.

**Comment by ThomasAribart** [comment]
@almondjelly since v1.19.1 you can use the (unified) event groups API! Search for "Event Groups" in the read me 👍

It works with both adapters so it will work seamlessly in your tests!

**Comment by ThomasAribart** [comment]
Closing this issue for the moment ! Re-open it if it doesn't match your needs !
